-- MySQL Script generated by MySQL Workbench
-- 03/01/17 17:26:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ezFlowDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ezFlowDB` ;

-- -----------------------------------------------------
-- Schema ezFlowDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ezFlowDB` DEFAULT CHARACTER SET utf8 ;
USE `ezFlowDB` ;

-- -----------------------------------------------------
-- Table `ezFlowDB`.`tSchool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezFlowDB`.`tSchool` ;

CREATE TABLE IF NOT EXISTS `ezFlowDB`.`tSchool` (
  `idtSchool` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idtSchool`),
  UNIQUE INDEX `idtSchool_UNIQUE` (`idtSchool` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezFlowDB`.`tCourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezFlowDB`.`tCourse` ;

CREATE TABLE IF NOT EXISTS `ezFlowDB`.`tCourse` (
  `idtCourse` INT NOT NULL AUTO_INCREMENT,
  `schoolCourseID` VARCHAR(45) NULL,
  `name` VARCHAR(100) NULL,
  `description` MEDIUMTEXT NULL,
  `credits` INT NULL,
  `courseLink` VARCHAR(45) NULL,
  `schoolID` INT NULL,
  PRIMARY KEY (`idtCourse`),
  UNIQUE INDEX `idtCourse_UNIQUE` (`idtCourse` ASC),
  INDEX `school_idx` (`schoolID` ASC),
  UNIQUE INDEX `schoolCoursesUnique` (`schoolID` ASC, `schoolCourseID` ASC),
  CONSTRAINT `school`
    FOREIGN KEY (`schoolID`)
    REFERENCES `ezFlowDB`.`tSchool` (`idtSchool`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezFlowDB`.`tPrerequisites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezFlowDB`.`tPrerequisites` ;

CREATE TABLE IF NOT EXISTS `ezFlowDB`.`tPrerequisites` (
  `parentID` INT NOT NULL,
  `prereqID` INT NOT NULL,
  INDEX `idtcourse_idx` (`parentID` ASC),
  INDEX `idtcourse_idx1` (`prereqID` ASC),
  PRIMARY KEY (`parentID`, `prereqID`),
  CONSTRAINT `parentCourse`
    FOREIGN KEY (`parentID`)
    REFERENCES `ezFlowDB`.`tCourse` (`idtCourse`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `prereqCourse`
    FOREIGN KEY (`prereqID`)
    REFERENCES `ezFlowDB`.`tCourse` (`idtCourse`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezFlowDB`.`tAdmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezFlowDB`.`tAdmin` ;

CREATE TABLE IF NOT EXISTS `ezFlowDB`.`tAdmin` (
  `idtAdmin` INT NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(45) NULL,
  `lName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `schoolID` INT NULL,
  `tokenID` VARCHAR (200) NULL,
  PRIMARY KEY (`idtAdmin`),
  UNIQUE INDEX `idtAdmin_UNIQUE` (`idtAdmin` ASC),
  INDEX `idtSchool_idx` (`schoolID` ASC),
  CONSTRAINT `idtSchool`
    FOREIGN KEY (`schoolID`)
    REFERENCES `ezFlowDB`.`tSchool` (`idtSchool`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezFlowDB`.`tMajors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezFlowDB`.`tMajors` ;

CREATE TABLE IF NOT EXISTS `ezFlowDB`.`tMajors` (
  `idtMajors` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `schoolID` INT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`idtMajors`),
  UNIQUE INDEX `idtMajors_UNIQUE` (`idtMajors` ASC),
  INDEX `schoolID_idx` (`schoolID` ASC),
  CONSTRAINT `schoolID`
    FOREIGN KEY (`schoolID`)
    REFERENCES `ezFlowDB`.`tSchool` (`idtSchool`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezFlowDB`.`tMajorCourses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezFlowDB`.`tMajorCourses` ;

CREATE TABLE IF NOT EXISTS `ezFlowDB`.`tMajorCourses` (
  `majorID` INT NOT NULL,
  `courseID` INT NOT NULL,
  PRIMARY KEY (`majorID`, `courseID`),
  INDEX `course_idx` (`courseID` ASC),
  CONSTRAINT `major`
    FOREIGN KEY (`majorID`)
    REFERENCES `ezFlowDB`.`tMajors` (`idtMajors`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `course`
    FOREIGN KEY (`courseID`)
    REFERENCES `ezFlowDB`.`tCourse` (`idtCourse`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO ezFlowServer;
 DROP USER ezFlowServer;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'ezFlowServer' IDENTIFIED BY 'JeK_yed384m=DR?T3VAmeJU=';

GRANT SELECT ON TABLE `ezFlowDB`.* TO 'ezFlowServer';
GRANT SELECT, INSERT, TRIGGER ON TABLE `ezFlowDB`.* TO 'ezFlowServer';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `ezFlowDB`.* TO 'ezFlowServer';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
